version: '3.9'

services:
  web:
      build: ./app
      command: sh ./commands.sh
      depends_on:
        - db
      expose:
        - 8000
      volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      env_file:
        - ./.env.dev
      restart: unless-stopped
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    restart: always
  
  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:80
volumes:
  postgres_volume:
  static_volume:
  media_volume: